#!/bin/bash
#set -x
# HEADER
###################################################################################################
# Author        : Robert McKenzie <rmckenzi@rpmdp.com>
# Description   : This will get a list of interfaces on the machine and either email or send by SMS
# Revision	: $Revision: 1.2 $
# Version       : $Header: /home/rmckenzi/Dropbox/sourcecode/RaspberryPi/RCS/send-myip,v 1.2 2013/05/22 12:24:20 rmckenzi Exp $
#
###################################################################################################

# Set the destination email address(es) here.  Add more using a comma then next address, etc
# You can also set the TO email from the command line as the second argument

# EDIT THIS NEXT LINE
EMAILTO=""

	if [ "$EMAILTO" = "" ];then
		echo ""
		echo "You must edit the script and set the EMAILTO variable to something"
		echo ""
		exit 1
	fi


HOSTNAME=`hostname`
SUBJECT="Your RPi ($HOSTNAME) is ready..."

# If you don't intend to use SMS you should set SMSTO to NOSMS, this will prevent the sendsms function to exit.
SMSTO=""

	if [ "$SMSTO" = "" ];then
		echo ""
		echo "You must edit the script and set the SMSTO variable to something"
		echo ""
		exit 1
	fi



###################################################################################################
# Functions start here
###################################################################################################

function getipinfo {

	ifaces=`ifconfig | grep "Link encap" | grep -v ^lo | awk '{print $1}'`

	for i in $ifaces
	do
		ip=`ifconfig $i  | grep "inet addr" | awk '{print $2}' | awk -F: '{print $2}'`
		echo "$i - $ip"
	done
}

function sendsms {

	if [ "$SMSTO" = "NOSMS" ];then
		exit 1
	fi

	MYIP=`getipinfo`

	# For info about the sms script I'm calling check out my blog:
	# http://www.uk-experience.com/2012/11/01/sending-sms-from-the-command-line/
	sms $SMSTO "Your RPi ($HOSTNAME) says, my IP is ... $MYIP"

}


function email {

# call the checkemail function to validate we have an email address to send to
checkemail

MYIP=`getipinfo`

# Do not indent these lines for script prettiness, it'll break the heardoc

mail $EMAILTO << EOF
To: $EMAILTO
Subject: $SUBJECT

Connect to your RPi ($HOSTNAME) with ...

$MYIP

EOF

}

function all {
	email
	sendsms
}

function help {

cat << EOF

You must provide 1 argment on the command line.

	sendsms	- This will ONLY send an sms to whoever you've set in the variables
	email	- This will ONLY send an email to whoever you've set in the variables
	all     - Send both Email and SMS
	help	- Display this page

	Other optional formats for the above arguments can be:

		--sendsms	| sendsms	| SENDSMS
		--email		| email		| EMAIL
		--all		| all		| ALL
		--help		| help		| HELP | (nothing at all)

	ie:	$0 --sendsms
		$0 EMAIL
		$0 --help

EOF

exit 0

}

function checkemail {

	if [ "$EMAILTO" = "" ]; then
		echo "************************************************************"
		echo "SCRIPT CONFIG ERROR"
		echo "************************************************************"
		echo ""
		echo "You either need to edit the script and put an email address"
		echo "into the TO variable near the top OR you must provide your"
		echo "email address as the second argument on the commandline"
		echo ""
		echo "************************************************************"
		exit 255
	fi

}



###################################################################################################
# End of the functions
###################################################################################################

# Display some help if you don't provide at least one command line argument.

case "$1" in

	--sendsms|sendsms|SENDSMS )
		sendsms
	;;

	--email|email|EMAIL )
		email
	;;

	--all|all|ALL )
		all
	;;

	* )
		help
	;;
esac



# FOOTER
###################################################################################################
#
# RCS Log
#
# $Log: send-myip,v $
# Revision 1.2  2013/05/22 12:24:20  rmckenzi
# Updated to include hostname of the PI .. we have more then one now :D
#
# Revision 1.1  2013/05/17 09:02:35  rmckenzi
# Initial revision
#
# Revision 1.7  2013/03/20 22:29:55  rmckenzi
# Added a way to prevent SMS code from being called by setting SMSTO to be NOSMS.
#
# Revision 1.6  2013/03/20 22:27:17  rmckenzi
# Cleaned up a few settings as well as added another check for SMS entry
#
# Revision 1.5  2013/03/17 23:59:20  rmckenzi
# Changed processing of some functions
# Added more valid email address checking to ensure we have someone to send to.
#
# Revision 1.4  2013/03/17 23:49:30  rmckenzi
# More help edits
#
# Revision 1.3  2013/03/17 23:47:56  rmckenzi
# Rewrote the help function and added better handing of command line arguments for added flexability.
#
# Revision 1.2  2013/03/17 23:23:30  rmckenzi
# Updated the mail function to be a bit more flexible with the message body format using a heredoc
#
# Revision 1.1  2013/03/17 22:28:19  rmckenzi
# Initial revision
#
#
###################################################################################################




