#!/bin/bash
#set -x
# HEADER
###################################################################################################
# Author        : Robert McKenzie <rmckenzi@rpmdp.com>
# Description   : This will get a list of interfaces on the machine and either email or send by SMS
#
###################################################################################################

# Set the destination email address(es) here.  Add more using a comma then next address, etc
# You can also set the TO email from the command line as the second argument

# EDIT THIS NEXT LINE
EMAILTO="rmckenzi@rpmdp.com"

	if [ "$EMAILTO" = "" ];then
		echo ""
		echo "You must edit the script and set the EMAILTO variable to something"
		echo ""
		exit 1
	fi


HOSTNAME=`hostname`
SUBJECT="Your RPi ($HOSTNAME) is ready..."
BODY=

# If you don't intend to use SMS you should set SMSTO to NOSMS, this will prevent the sendsms function to exit.
SMSTO="NOSMS"

	if [ "$SMSTO" = "" ];then
		echo ""
		echo "You must edit the script and set the SMSTO variable to something"
		echo ""
		exit 1
	fi



###################################################################################################
# Functions start here
###################################################################################################


function ipinfo {

	# Internal IP(s)
	MYIPTMP=`getipinfo`
	MYIP="Int IP: $MYIPTMP"

	# External facing IP info
	MYEXTIPTMP=`wget http://ipecho.net/plain -O - -q ; echo`
	MYEXTIP="Ext IP: $MYEXTIPTMP"

}
	

function getipinfo {

	ifaces=`ifconfig | grep "Link encap" | grep -v ^lo | awk '{print $1}'`

	for i in $ifaces
	do
		ip=`ifconfig $i  | grep "inet addr" | awk '{print $2}' | awk -F: '{print $2}'`
		echo "$i - $ip"
	done
}

function sendsms {

	if [ "$SMSTO" = "NOSMS" ];then
		exit 1
	fi

	# For info about the sms script I'm calling check out my blog:
	# http://www.uk-experience.com/2012/11/01/sending-sms-from-the-command-line/
	sms $SMSTO "Your RPi ($HOSTNAME) says, my IP is ... $MYIP / $MYEXTIP"
}


function email {

# call the checkemail function to validate we have an email address to send to
checkemail

# Do not indent these lines for script prettiness, it'll break the heardoc

mail $EMAILTO << EOF
To: $EMAILTO
Subject: $SUBJECT

Connect to your RPi ($HOSTNAME) with ...

$MYIP
$MYEXTIP

EOF

}

function help {

cat << EOF

You must provide 1 argment on the command line.

	sendsms	- This will ONLY send an sms to whoever you've set in the variables
	email	- This will ONLY send an email to whoever you've set in the variables
	all     - Send both Email and SMS
	help	- Display this page

	Other optional formats for the above arguments can be:

		--sendsms	| sendsms	| SENDSMS
		--email		| email		| EMAIL
		--all		| all		| ALL 

		This option is only for testing or local use and is not included in the --all option
		--display	| display	| DISPLAY

		--help		| help		| HELP | (nothing at all)

	ie:	$0 --sendsms
		$0 EMAIL
		$0 --help

EOF

exit 0

}

function checkemail {

	if [ "$EMAILTO" = "" ]; then
		echo "************************************************************"
		echo "SCRIPT CONFIG ERROR"
		echo "************************************************************"
		echo ""
		echo "You either need to edit the script and put an email address"
		echo "into the TO variable near the top OR you must provide your"
		echo "email address as the second argument on the commandline"
		echo ""
		echo "************************************************************"
		exit 255
	fi

}



###################################################################################################
# End of the functions
###################################################################################################

# Display some help if you don't provide at least one command line argument.

case "$1" in

	--sendsms|sendsms|SENDSMS )
		ipinfo
		sendsms
	;;

	--email|email|EMAIL )
		ipinfo
		email
	;;

	--all|all|ALL )
		ipinfo
		email
		sendsms
	;;

	--display|display|DISPLAY )
		ipinfo
		echo "---------------------------------------------------"
		echo "$MYIP"
		echo "$MYEXTIP"
		echo "---------------------------------------------------"
	;;

	* )
		help
	;;
esac


